Changed all occurrences of CANDLE_WRAPPERS to CANDLE/wrappers

diff --git a/templates/scripts/candle-import-template b/templates/scripts/candle-import-template
--- a/templates/scripts/candle-import-template
+++ b/templates/scripts/candle-import-template
@@ -16,5 +16,5 @@ if [ ! $? -eq 0 ]; then
 # ...otherwise, copy over the corresponding template files
 else
     template_lower=$(echo $template | awk '{print(tolower($0))}')
-    cp $CANDLE_WRAPPERS/templates/examples/$template_lower/* . && echo "done" || echo "failed"
+    cp $CANDLE/wrappers/templates/examples/$template_lower/* . && echo "done" || echo "failed"
 fi
